# Name the node stage "installer"
FROM ubuntu:bionic AS installer
LABEL maintainer="Sebastian Spreizer <spreizer@web.de>"

RUN apt-get update && apt-get install -y python3-pip
RUN python3 -m pip install --upgrade pip uwsgi

RUN export LC_CTYPE=C.UTF-8 && \
    python3 -m pip install -i https://test.pypi.org/simple/ nest-desktop==3.0.0.dev3 && \
    ls /usr/local/lib/python3.6/dist-packages/nest_desktop


# nginx state for serving content
FROM nginx:alpine

# Set working directory to nginx asset directory
WORKDIR /usr/share/nginx/html

# Remove default nginx static assets
RUN rm -rf ./*

# Copy static from installer stage
COPY --from=installer /usr/local/lib/python3.6/dist-packages/nest_desktop/app/ .

# Add default to available sites
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8000

# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]
